Config:
  Module:
    Announce: false
    TimedTask: true
    Bank: true
    Bar: true
    Bitcoin: false
    CItems: true
    Shulker: true
    Logs: false
  #Custom command module
  Commands:
    Discord: |
      '&8&m-------------------------------------'
      ' &r &d&lDiscord &8&l▪ &bhttps://oxaliamc.fr/discord'
      '&8&m-------------------------------------'
    Link: |
      '&8&m-------------------------------------'
      ' &r &d&lDiscord &8&l▪ &bhttps://oxaliamc.fr/discord'
      ' &r &a&lSite &8&l▪ &bhttps://oxaliamc.fr/'
      ' &r &9&lVote &8&l▪ &bhttps://oxaliamc.fr/vote'
      ' &r &b&lBoutique &8&l▪ &bhttps://oxaliamc.fr/boutique'
      '&8&m-------------------------------------'
    Site: |
      '&8&m-------------------------------------'
      ' &r &a&lSite &8&l▪ &bhttps://oxaliamc.fr/'
      '&8&m-------------------------------------'
    Store: |
      '&8&m-------------------------------------'
      ' &r &b&lBoutique &8&l▪ &bhttps://oxaliamc.fr/boutique'
      '&8&m-------------------------------------'
    Vote: |
      '&8&m-------------------------------------'
      ' &r &9&lVote &8&l▪ &bhttps://oxaliamc.fr/vote'
      '&8&m-------------------------------------'
    Furnace:
      Success: "&b&lFurnace &8&l▪ &aVous avez cuit vos minerais."
      NoMaterial: "&b&lFurnace &8&l▪ &cVous n'avez rien à cuire."
      Article:
        1:
          Base: COAL_ORE
          Result: COAL
        2:
          Base: DEEPSLATE_COAL_ORE
          Result: COAL
        3:
          Base: IRON_ORE
          Result: IRON_INGOT
        4:
          Base: DEEPSLATE_IRON_ORE
          Result: IRON_INGOT
        5:
          Base: COPPER_ORE
          Result: COPPER_INGOT
        6:
          Base: DEEPSLATE_COPPER_ORE
          Result: COPPER_INGOT
        7:
          Base: GOLD_ORE
          Result: GOLD_INGOT
        8:
          Base: DEEPSLATE_GOLD_ORE
          Result: GOLD_INGOT
        9:
          Base: REDSTONE_ORE
          Result: REDSTONE
        10:
          Base: DEEPSLATE_REDSTONE_ORE
          Result: REDSTONE
        11:
          Base: EMERALD_ORE
          Result: EMERALD
        12:
          Base: DEEPSLATE_EMERALD_ORE
          Result: EMERALD
        13:
          Base: LAPIS_ORE
          Result: LAPIS_LAZULI
        14:
          Base: DEEPSLATE_LAPIS_ORE
          Result: LAPIS_LAZULI
        15:
          Base: DIAMOND_ORE
          Result: DIAMOND
        16:
          Base: DEEPSLATE_DIAMOND_ORE
          Result: DIAMOND
        17:
          Base: NETHER_GOLD_ORE
          Result: GOLD_INGOT
        18:
          Base: NETHER_QUARTZ_ORE
          Result: QUARTZ
        19:
          Base: ANCIENT_DEBRIS
          Result: NETHERITE_SCRAP
  #Announcer module to send message to all player
  Announcer:
    Enable: true #If true the announcer module will work and send a message every X seconds
    Interval: 600 #In seconds
    Messages:
      - "&6&lAnnonce &8&l▪ &7N'hésitez pas à faire la commande &b/menu &7afin de découvrir les &efonctionalités du serveur&7."
      - "&6&lAnnonce &8&l▪ &7N'hésitez pas à faire la commande &b/craftcustoms &7pour connaître tout &eles nouveaux crafts&7."
      - "&6&lAnnonce &8&l▪ &7N'hésitez pas à faire la commande &b/options &7et réglez tout &evos réglages&7."
      - "&6&lAnnonce &8&l▪ &7N'hésitez pas à faire la commande &b/contrat &7afin de faire &evos missions&7."
      - "&6&lAnnonce &8&l▪ &7N'hésitez pas à faire la commande &b/rangs &7pour bénéficier de &enouveaux avantages&7."
      - "&6&lAnnonce &8&l▪ &7N'hésitez pas à faire la commande &b/kits &7pour réclamer &evos kits&7."
  #Shulker Module to open from inventory
  Shulker:
    Permission: OxaliaCore.Shulker.Open
    Message:
      NoPerm: '&d&lShulker &8&l▪ &cVous n''avez pas la permission d''ouvrir cette shulker.'
  #Global messages
  Messages:
    Help: '&c&lOxalia&6&lMc &8&l▪ &7Utilisez &a/oxaliacore &eHelp&7.'
    NoPerm: '&c&lOxalia&6&lMc &8&l▪ &cVous n''avez pas la permission.'
    Reload: '&c&lOxalia&6&lMc &8&l▪ &aLe plugin vient d''être rechargé.'