name: OxaliaCore
version: 1.0.0
author: Hamunaptra_
api-version: 1.13

main: fr.hamunaptra_.oxaliacore.Main

commands:
  bar:
    description: Customs Bar Modules
  citems:
    description: Customs Items module
  bank:
    description: Customs Bank module
    aliases:
      - banque