name: OxaliaCore
version: 0.1.6.1-BETA
author: Halbrand__
api-version: 1.13

main: fr.hamunaptra_.oxaliacore.Main

commands:
  cos:
    description: cc module
  bar:
    description: Bar module
  bank:
    description: Bank module
    aliases:
      - banque
  citems:
    description: CItems module
  deletelog:
    description: Log module command
  #Commands Module
  clearreloadall:
    description: ClearLag & ClearLagTimer Reload Command
  chatclear:
    description: ChatClear Command
  discord:
    description: Discord Command
  furnace:
    description: Smelt ore Command
  link:
    description: Link Command
    aliases:
      - lien
  site:
    description: Site Command
  store:
    description: Store Command
    aliases:
      - boutique
  votes:
    description: Vote Command
  viewlog:
    description: Vote Command
  oxaliacore:
    description: Reload plugin Command